# Generated by Django 4.1 on 2024-11-15 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
    ]
