# Generated by Django 4.1 on 2024-11-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_factura_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
