# Generated by Django 4.1 on 2024-11-17 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_factura_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='estado',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{0,10}$')]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
